### ISSUE TITLE
assess the quality of generated NetCDFs (thies and parsivel)

### ISSUE THREAD

**Issue by andrecastro0o** [ruisdael-observatory/disdroDL#2]
assess the quality of generated NetCDFs (thies and parsivel) since the CS2000 development process has ended.

write down any issues that might be present in NetCDF
and evaluate fixes(now, or future release)

**Comment by andrecastro0o** [comment]
# 2024.07.22 Parsive and Thies NetCDFs

@mschleiss The following files were captured during 2024.07.22 (less than 24h as I started the loggers around 2pm)

At first glance they look good. I will try to pass them through NCQC checks.

If you have feedback on the files, just add it to the issue 

* [20240722_Green_Village-GV_PAR008.nc](https://ruisdael.citg.tudelft.nl/parsivel/PAR008_GreenVillage/2024/202407/20240722_Green_Village-GV_PAR008.nc)
* [20240722_Green_Village-GV_THIES006.nc](https://ruisdael.citg.tudelft.nl/thies/Thies006_Green_Village/2024/202407/20240722_Green_Village-GV_THIES006.nc)

**Comment by andrecastro0o** [comment]
@mschleiss On 2024.08.03 there was a bit of rain. I am including here the NetCDFs for both the Parsivel and the Thies from the GV, which results from DisdroDL v0.3.0 (this repo) 

* https://ruisdael.citg.tudelft.nl/parsivel/PAR008_GreenVillage/2024/202408/20240803_Green_Village-GV_PAR008.nc
* https://ruisdael.citg.tudelft.nl/thies/Thies006_Green_Village/2024/202408/20240803_Green_Village-GV_THIES006.nc
 
When you have the time have a look at them and report here if you find any issues with the files. Cheers!

**Comment by andrecastro0o** [comment]
More days with rain:
* https://ruisdael.citg.tudelft.nl/thies/Thies006_Green_Village/2024/202408/20240813_Green_Village-GV_THIES006.nc
* https://ruisdael.citg.tudelft.nl/parsivel/PAR008_GreenVillage/2024/202408/20240813_Green_Village-GV_PAR008.nc

**Comment by mschleiss** [comment]
I checked the data and metadata for 2024-08-14 and noticed 6 issues, in decreasing order of importance:

**Issue 1:** There are some backslashes in the metadata description of variable "weather_code_metar_4678_5min" that need to be removed:

string weather_code_metar_4678_5min\ \(unitless\)(time) ;
		string weather_code_metar_4678_5min\ \(unitless\):_FillValue = "" ;
		weather_code_metar_4678_5min\ \(unitless\):long_name = "5-minute METAR Tab.4678 code" ;
		weather_code_metar_4678_5min\ \(unitless\):standard_name = "weather_code_metar_4678_5min (unitless)" ;
		weather_code_metar_4678_5min\ \(unitless\):comment = "See Table 7: Code SYNOP/METAR in the documentation for possible values" ;

**Issue 2:** In the datetime time series, I noticed some strange characters "+00:00" at the end of each date/time. The purpose of these characters is unclear to me and I suggest to remove them.

datetime = "2024-08-14T00:00:00.717944+00:00", 
    "2024-08-14T00:01:00.222662+00:00", "2024-08-14T00:02:00.702306+00:00", ..
    
**Issue 3:** Variable: total_volume_gross_of_class_1:long_name = "Total volume (gross) of class 1 (unitless)" is given as uniteless. However, volume should have a unit. Same comment for all the other total_volume_gross variables. Please check the unit of all these variables and include it in the metadata description.

**Issue 4:** Some variables could use data type int instead of float. This is a minor issue but could save some storage space during compression. For example all variables with names "number_of_particles_xxx" could be of type int. Also, the interior temperature variable could be int, as well as many of the control output variables for voltage, heating, power supply etc.. 

**Issue 5:** I noticed an inconsistency in the way the long_names are given. For some variables, the long names include the units. For example, long_name = "Interior temperature [°C]", while for others, it doesn't (e.g., long_name = "1-minute radar reflectivity"). Since there does not appear to be any clear rule for how to handle this, I suggest to provide the units in the long names whenever possible. This may be redundant given that there is also a unit attribute but could be useful if people use the long name as input to plot the data.
    
**Issue 6:** There is a small inconsistency in the way the comments for the weather codes are given.
For variables "weather_code_synop_4680" and "weather_code_metar_4678", the comment field states: "Possible values in Thies documentation: Table 7: Code table SYNOP/METAR". I suggest to change this text to the default sentence used for all the other weather codes: "See Table 7: Code SYNOP/METAR in the documentation for possible values"

**Comment by andrecastro0o** [comment]
@mschleiss  I will create separate issues for each of the first 4 items and will ask you to review the pull request

**Comment by andrecastro0o** [comment]
For the BS variables, with no relevant data, let's remove them from the config file and they wont be included in the NetCDF. I will create an issue for that.

**Comment by andrecastro0o** [comment]
I will tackle the changes requested by @mschleiss in separate issues and Pull Requests, merged on to to branch 0.3.2. 

Once all changes have been merged on branch 0.3.2, that branch shall be merged to main and a new release created

**Comment by andrecastro0o** [comment]
* issue 1: tackled in #13 
* issue 3: tackled in #14 
* issue 4: tackled in #15
* issue 5: tackled in #16
* issue 6: tackled in #17
* thies vars to be removed: tackled in #18

**Comment by andrecastro0o** [comment]
@mschleiss after these changes were implemented, the resulting NetCDFs are coming in. Here is the link for yesterday NetCDF https://ruisdael.citg.tudelft.nl/thies/Thies006_Green_Village/2024/202408/20240825_Green_Village-GV_THIES006.nc

I fell confident to merge the changes from  https://github.com/ruisdael-observatory/disdroDL/pull/25

**Comment by mschleiss** [comment]
Looks good to me. The only (minor) issue I noticed concerns the fact that some of the variables could be encoded as integers instead of floats.

Variables that could be encoded as an **unsigned** 32 bit integer instead of a float:
- visiblity

Variables that could be encoded as **unsigned** 16 bit integer instead of a float:
- mean_value_laser_current
- control_voltage
- optical_control_output

Variables that could be encoded as an **unsigned** 8-bit integer:
- measurement quality
- current_heating_laser_head
- current_heating_receiver_head

Variables that could be encoded as a **signed** 8-bit integer:
- interior_temperature
- temperature_laser_driver


Not sure how much control you have over the type of integer. At least, we could use 32 bit integers for most of the variables above and 8 bit integers for the variables whose values range between 0-100.

**Comment by andrecastro0o** [comment]
@mschleiss concerning the previous comment, the issue with doing this is that if these variables' values,  are not encoded as integers by the Thies telegram, we will need to get into the source code and perform conversions to each one of them. 
It will be a substantial effort, for not much gain. The Thies NetCDF files are relatively small, hence this does not seem to be a priority

**Comment by andrecastro0o** [comment]
Variables that could be encoded as an unsigned 32 bit integer instead of a float:
* visibility:
   * field number: 18
   * example: `18:99999`
   * needs conversion: UNSURE

Variables that could be encoded as unsigned 16 bit integer instead of a float:
* mean_value_laser_current:
   * field number: 40
   * example: 40:1778
   * needs conversion:  NO
* control_voltage:
   * field number: 41
   * example:  41:4011
   * needs conversion:  NO
* optical_control_output
   * field number: 42
   * example:  42:2772
   * needs conversion:  NO

Variables that could be encoded as an unsigned 8-bit integer:
* measurement_quality
   * field number: 20
   * example:  22:0
   * needs conversion:  NO
* current_heating_laser_head
   * field number: 44
   * example:  `44:028;`
   * needs conversion:  NO
* current_heating_receiver_head
   * field number: 45
   * example: `45:034`
   * needs conversion:  NO
   
Variables that could be encoded as a signed 8-bit integer:
* interior_temperature
   * field number: 38
   * example: `38:+33`
   * needs conversion:  NO
* temperature_of_laser_driver
   * field number: 39
   * example: `39:37`
   * needs conversion:  NO


Alright @mschleiss you did your home work :) all of these vars are encoded as ints in the telegram. Hence tey shall be easy to store as ints in the NetCDF. I will give it a go

**Comment by mschleiss** [comment]
@andrecastro0o You scared me for a while. I thought that we were doing some rounding on floats during the logging. I understand that logging everything as a float is the easier and faster solution. But the general philosophy should be: if the variable is given as an integer in the telegram, it should be logged as an integer in the NetCDF as well. The type of integer is not super important and won't make a huge difference in terms of storage space. But hey, I grew up in a time where memory was expensive. If something only varies between 0-100, a 8-bit integer shall be used :-)

**Comment by andrecastro0o** [comment]
> @andrecastro0o You scared me for a while. I thought that we were doing some rounding on floats during the logging. I understand that logging everything as a float is the easier and faster solution. But the general philosophy should be: if the variable is given as an integer in the telegram, it should be logged as an integer in the NetCDF as well. The type of integer is not super important and won't make a huge difference in terms of storage space. But hey, I grew up in a time where memory was expensive. If something only varies between 0-100, a 8-bit integer shall be used :-)

@mschleiss. Sorry for the scare. I agree with only, not so much in terms of storage saving, but in relation to consistency - the vars values shouldn't be stored as floats if in their source they are ints.
